// <auto-generated />
#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using MediaBrowser.Common.Net;
using Microsoft.Extensions.Logging;
using MulletaFlix.Data.Enums;
using MediaBrowser.Common.Configuration;
using MediaBrowser.Controller;
using MediaBrowser.Controller.Entities;
using MediaBrowser.Controller.Library;
using MediaBrowser.Controller.LiveTv;
using MediaBrowser.Model.Configuration;
using MediaBrowser.Model.Entities;
using MediaBrowser.Model.LiveTv;
using MediaBrowser.Model.Tasks;
using MediaBrowser.Providers.Plugins.MidiaStorageOnline.Configuration;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline.ScheduledTasks
{
    public class MidiaStorageOnlineSyncTask : IScheduledTask
    {
        // BG-1: bounded parallelism â€” ProcessorCount*2 vs old 256
        private static readonly int _maxParallelism = Math.Max(4, Environment.ProcessorCount * 2);

        // BG-2: allocate once
        private static readonly char[] _invalidFileNameChars = Path.GetInvalidFileNameChars();

        // BG-3: compiled regex
        private static readonly Regex _epRegex = new(
            @"^(.*?)\s+S(\d+)\s*E(\d+)(?:\s+(.*))?$",
            RegexOptions.IgnoreCase | RegexOptions.Compiled);

        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfigurationManager _configurationManager;
        private readonly IServerApplicationHost _serverApplicationHost;
        private readonly ILibraryManager _libraryManager;
        private readonly ITunerHostManager _tunerHostManager;
        private readonly ILogger<MidiaStorageOnlineSyncTask> _logger;

        public MidiaStorageOnlineSyncTask(
            IHttpClientFactory httpClientFactory,
            IConfigurationManager configurationManager,
            IServerApplicationHost serverApplicationHost,
            ITunerHostManager tunerHostManager,
            ILibraryManager libraryManager,
            ILogger<MidiaStorageOnlineSyncTask> logger)
        {
            _httpClientFactory = httpClientFactory;
            _configurationManager = configurationManager;
            _serverApplicationHost = serverApplicationHost;
            _tunerHostManager = tunerHostManager;
            _libraryManager = libraryManager;
            _logger = logger;
        }

        public string Name => "Sincronizar Midia Online";
        public string Key => "MidiaStorageOnlineSync";
        public string Description => "Baixa lista M3U, classifica entradas e gera arquivos .strm";
        public string Category => "Midia Storage Online";

        public Task ExecuteAsync(IProgress<double> progress, CancellationToken cancellationToken)
        {
            var config = Plugin.Instance!.Configuration;
            if (string.IsNullOrEmpty(config.M3uUrl))
            {
                Log("URL M3U nao configurada. Agende via plugin.");
                return Task.CompletedTask;
            }
            return SyncInternal(config, progress, cancellationToken);
        }

        private static readonly object ManifestLock = new object();

        private Dictionary<string, string> LoadManifest()
        {
            var dir = Path.Combine(Plugin.AppPaths.ProgramDataPath, "midia-online");
            var path = Path.Combine(dir, "sync_manifest.json");
            lock (ManifestLock)
            {
                if (!System.IO.File.Exists(path))
                    return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                try
                {
                    var json = System.IO.File.ReadAllText(path);
                    return System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, string>>(json) 
                           ?? new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }
                catch (Exception ex)
                {
                    Log($"Erro ao carregar manifesto: {ex.Message}. Criando novo.");
                    return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
                }
            }
        }

        private void SaveManifest(Dictionary<string, string> manifest)
        {
            var dir = Path.Combine(Plugin.AppPaths.ProgramDataPath, "midia-online");
            Directory.CreateDirectory(dir);
            var path = Path.Combine(dir, "sync_manifest.json");
            lock (ManifestLock)
            {
                try
                {
                    var json = System.Text.Json.JsonSerializer.Serialize(manifest, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
                    System.IO.File.WriteAllText(path, json);
                }
                catch (Exception ex)
                {
                    Log($"Erro ao salvar manifesto: {ex.Message}");
                }
            }
        }

        private void NormalizeMidiaStorageOnlineTunerHost(string tunerUrl, string tunerId)
        {
            var liveTvConfig = _configurationManager.GetConfiguration<LiveTvOptions>("livetv");
            var tunerHosts = liveTvConfig.TunerHosts.ToList();
            var matchingHosts = tunerHosts
                .Where(h =>
                    string.Equals(h.Type, "m3u", StringComparison.OrdinalIgnoreCase)
                    && string.Equals(h.Url, tunerUrl, StringComparison.OrdinalIgnoreCase)
                    && string.Equals(h.FriendlyName, "Midia Storage Online (Canais)", StringComparison.OrdinalIgnoreCase))
                .ToList();

            if (matchingHosts.Count == 0)
            {
                return;
            }

            var primary = matchingHosts.FirstOrDefault(h => string.Equals(h.Id, tunerId, StringComparison.OrdinalIgnoreCase)) ?? matchingHosts[0];
            primary.Id = tunerId;
            primary.Type = "m3u";
            primary.Url = tunerUrl;
            primary.FriendlyName = "Midia Storage Online (Canais)";
            primary.TunerCount = 0;
            primary.AllowHWTranscoding = true;
            primary.AllowStreamSharing = true;
            primary.EnableStreamLooping = false;
            primary.AllowFmp4TranscodingContainer = false;
            primary.FallbackMaxStreamingBitrate = 30000000;
            primary.IgnoreDts = true;
            primary.ReadAtNativeFramerate = false;

            var normalizedHosts = tunerHosts
                .Where(h =>
                    !(string.Equals(h.Type, "m3u", StringComparison.OrdinalIgnoreCase)
                      && string.Equals(h.Url, tunerUrl, StringComparison.OrdinalIgnoreCase)
                      && string.Equals(h.FriendlyName, "Midia Storage Online (Canais)", StringComparison.OrdinalIgnoreCase)))
                .ToList();
            normalizedHosts.Add(primary);
            liveTvConfig.TunerHosts = normalizedHosts.ToArray();
            _configurationManager.SaveConfiguration("livetv", liveTvConfig);
        }

        private async Task SyncInternal(PluginConfiguration config, IProgress<double> progress, CancellationToken ct)
        {
            try
            {
                Log("Iniciando sync automatico...");

                var baseUrl = _serverApplicationHost.GetSmartApiUrl("localhost");
                MidiaStorageOnlineStreamProxy.LocalBaseUrl = baseUrl;

                var sw = System.Diagnostics.Stopwatch.StartNew();
                progress.Report(5);

                var m3uRaw = await DownloadM3U(config.M3uUrl!, ct).ConfigureAwait(false);
                progress.Report(30);

                var entries = ParseM3u(m3uRaw, out var headerLine);
                entries = MidiaStorageOnlineEntryDeduplicator.DeduplicateByKey(entries, BuildEntryDedupKey).ToList();
                Log($"Entries deduplicadas: {entries.Count} entradas ativas.");
                Log($"Parsed: {entries.Count} entradas");
                progress.Report(50);

                // 1. Processar e cadastrar os canais imediatamente apÃ³s o parse do M3U
                var channelEntries = entries
                    .Where(e => e.Type == "Canal")
                    .ToList();

                try
                {
                    await MidiaStorageOnlineLogoLibrary.EnsureChannelLogosAsync(
                        channelEntries,
                        baseUrl,
                        ct).ConfigureAwait(false);
                }
                catch (Exception logoEx)
                {
                    Log($"Falha ao resolver logos dos canais: {logoEx.Message}");
                }

                var canaisM3u = new StringBuilder();
                canaisM3u.Append(headerLine);
                foreach (var entry in channelEntries)
                {
                    AppendEntryLinesWithInferredTvgId(canaisM3u, entry);
                }

                var canaisContent = MidiaStorageOnlineStreamProxy.NormalizeM3uContent(canaisM3u.ToString());
                config.TotalChannelCount = entries.Count(e => e.Type == "Canal");
                config.EpgCompatibleChannelCount = entries.Count(e => e.Type == "Canal" && !string.IsNullOrWhiteSpace(GetEffectiveTvgId(e)));
                Plugin.Instance!.UpdateConfiguration(config);

                // BG-5: save canais to dedicated file ONLY, do NOT serialize into config.xml
                var canaisFilePath = GetCanaisFilePath();
                Directory.CreateDirectory(Path.GetDirectoryName(canaisFilePath)!);
                await System.IO.File.WriteAllTextAsync(canaisFilePath, canaisContent, ct).ConfigureAwait(false);

                // Cadastrar/atualizar sintonizador imediatamente
                var tunerUrl = $"{baseUrl}/MidiaStorageOnline/m3u/canais";
                try
                {
                    var tuner = new TunerHostInfo
                    {
                        Id = config.TunerHostId,
                        Type = "m3u",
                        Url = tunerUrl,
                        FriendlyName = "Midia Storage Online (Canais)",
                        TunerCount = 0,
                        AllowHWTranscoding = true
                    };
                    var saved = await _tunerHostManager.SaveTunerHost(tuner).ConfigureAwait(false);
                    config.TunerHostId = saved.Id;
                    Plugin.Instance!.UpdateConfiguration(config);
                    NormalizeMidiaStorageOnlineTunerHost(tunerUrl, saved.Id);
                    Log($"Sintonizador registrado imediatamente: {tunerUrl} (ID: {saved.Id})");
                }
                catch (Exception tunerEx)
                {
                    Log($"Falha ao registrar sintonizador M3U: {tunerEx}");
                    config.LastSyncError = $"Falha ao registrar sintonizador M3U: {tunerEx.Message}";
                    Plugin.Instance!.UpdateConfiguration(config);
                }

                var epgConfigured = !string.IsNullOrWhiteSpace(config.EpgUrl);
                if (config.EnableAutoEpg || epgConfigured)
                {
                    try
                    {
                        string? guidePath;
                        if (config.EnableAutoEpg)
                        {
                            guidePath = await AutoFetchEpgAsync(config, entries, ct).ConfigureAwait(false);
                        }
                        else
                        {
                            guidePath = await EnsureEpgGuideAsync(config, ct).ConfigureAwait(false);
                        }
                        if (!string.IsNullOrEmpty(guidePath))
                        {
                            RegisterXmlTvListingProvider(guidePath, config);
                        }
                    }
                    catch (Exception epgEx)
                    {
                        config.EpgLastError = epgEx.Message;
                        Plugin.Instance!.UpdateConfiguration(config);
                        Log($"Falha ao sincronizar XMLTV/EPG: {epgEx.Message}");
                    }
                }
                else
                {
                    config.EpgLastError = null;
                }

                // 2. Criar pastas e preparar bibliotecas para filmes e series
                var strmPath = GetStrmOutputPath(config);
                var moviesPath = Path.Combine(strmPath, "Filmes");
                var seriesPath = Path.Combine(strmPath, "Series");

                Directory.CreateDirectory(moviesPath);
                Directory.CreateDirectory(seriesPath);

                // Count upfront to create libraries before file processing
                int entryMovieCount = entries.Count(e => e.Type == "Filme");
                int entrySeriesCount = entries.Count(e => e.Type == "Serie");

                var existingLibs = _libraryManager.GetVirtualFolders().Select(v => v.Name).ToHashSet();
                try
                {
                    if (!existingLibs.Contains("Filmes") && entryMovieCount > 0)
                    {
                        await _libraryManager.AddVirtualFolder("Filmes", CollectionTypeOptions.movies,
                            new LibraryOptions { PathInfos = new[] { new MediaPathInfo(moviesPath) } }, true).ConfigureAwait(false);
                        Log("Biblioteca 'Filmes' criada");
                    }
                    if (!existingLibs.Contains("Series") && entrySeriesCount > 0)
                    {
                        await _libraryManager.AddVirtualFolder("Series", CollectionTypeOptions.tvshows,
                            new LibraryOptions { PathInfos = new[] { new MediaPathInfo(seriesPath) } }, true).ConfigureAwait(false);
                        Log("Biblioteca 'Series' criada");
                    }
                }
                catch (Exception libEx)
                {
                    Log($"Falha ao criar bibliotecas virtuais: {libEx}");
                    config.LastSyncError = $"Falha ao criar bibliotecas virtuais: {libEx.Message}";
                    Plugin.Instance!.UpdateConfiguration(config);
                }

                var manifest = LoadManifest();
                // Initialize with existing manifest to preserve files that are not in the new M3U
                var newManifest = new System.Collections.Concurrent.ConcurrentDictionary<string, string>(manifest, StringComparer.OrdinalIgnoreCase);
                var createdDirs = new System.Collections.Concurrent.ConcurrentDictionary<string, byte>(StringComparer.OrdinalIgnoreCase);

                var totalSynced = 0;
                int movieCount = 0, seriesCount = 0, skippedCount = 0;

                // Loop paralelo somente para filmes e series
                var movieAndSeriesEntries = entries.Where(e => e.Type == "Filme" || e.Type == "Serie").ToList();

                // BG-1: bounded parallelism
                await Parallel.ForEachAsync(movieAndSeriesEntries, new ParallelOptions { MaxDegreeOfParallelism = _maxParallelism }, async (entry, token) =>
                {
                    try
                    {
                        token.ThrowIfCancellationRequested();

                        if (entry.Type == "Filme")
                        {
                            var name = SanitizeName(entry.Name);
                            var relPath = Path.Combine("Filmes", name, name + ".strm");
                            var filePath = Path.Combine(strmPath, relPath);
                            var newUrl = entry.Url.Trim();

                            newManifest[relPath] = newUrl;

                            var fileExists = System.IO.File.Exists(filePath);
                            if (fileExists)
                            {
                                Log($"Sobrescrevendo .strm: {filePath}");
                            }

                            var dir = Path.Combine(moviesPath, name);
                            Directory.CreateDirectory(dir);
                            createdDirs.TryAdd(dir, 0);
                            var fileParentDir = Path.GetDirectoryName(filePath);
                            if (!string.IsNullOrWhiteSpace(fileParentDir))
                            {
                                Directory.CreateDirectory(fileParentDir);
                            }
                            await System.IO.File.WriteAllTextAsync(filePath, newUrl, token).ConfigureAwait(false);
                            Interlocked.Increment(ref totalSynced);
                            Interlocked.Increment(ref movieCount);
                        }
                        else if (entry.Type == "Serie")
                        {
                            var showName = SanitizeName(entry.ShowName);
                            var name = SanitizeName(entry.Name);
                            var seasonFolder = SanitizeName(entry.Season);
                            var relPath = Path.Combine("Series", showName, seasonFolder, name + ".strm");
                            var filePath = Path.Combine(strmPath, relPath);
                            var newUrl = entry.Url.Trim();

                            newManifest[relPath] = newUrl;

                            var fileExists = System.IO.File.Exists(filePath);
                            if (fileExists)
                            {
                                Log($"Sobrescrevendo .strm: {filePath}");
                            }

                            var dir = Path.Combine(seriesPath, showName, seasonFolder);
                            Directory.CreateDirectory(dir);
                            createdDirs.TryAdd(dir, 0);
                            var fileParentDir = Path.GetDirectoryName(filePath);
                            if (!string.IsNullOrWhiteSpace(fileParentDir))
                            {
                                Directory.CreateDirectory(fileParentDir);
                            }
                            await System.IO.File.WriteAllTextAsync(filePath, newUrl, token).ConfigureAwait(false);
                            Interlocked.Increment(ref totalSynced);
                            Interlocked.Increment(ref seriesCount);
                        }
                    }
                    catch (Exception entryEx)
                    {
                        Log($"Falha ao processar entrada '{entry.Name}': {entryEx}");
                    }
                }).ConfigureAwait(false);

                // Requerido pelo usuÃ¡rio: NÃ£o deletar nenhum arquivo ausente da playlist M3U, apenas manter e atualizar se houver alteraÃ§Ãµes
                var deletedCount = 0;

                // Save manifest
                var manifestToSave = new Dictionary<string, string>(newManifest, StringComparer.OrdinalIgnoreCase);
                SaveManifest(manifestToSave);

                config.LastSyncTime = DateTime.UtcNow;
                config.SyncedFileCount = newManifest.Count;
                config.LastSyncError = null;
                Plugin.Instance!.UpdateConfiguration(config);

                await UpdateLiveTvChannelItemsAsync(channelEntries, ct).ConfigureAwait(false);

                progress.Report(80);
                Log($"Sync automatico OK em {sw.Elapsed.TotalSeconds:F1}s: {totalSynced} salvos, {skippedCount} ignorados, {deletedCount} deletados, canais M3U {canaisM3u.Length / 1024}KB");

                progress.Report(100);
            }
            catch (Exception ex)
            {
                Log($"Erro: {ex}");
                config.LastSyncError = ex.Message;
                Plugin.Instance!.UpdateConfiguration(config);
            }
        }

        private async Task<string> DownloadM3U(string url, CancellationToken ct)
        {
            for (var attempt = 0; attempt <= 2; attempt++)
            {
                try
                {
                    using var client = _httpClientFactory.CreateClient();
                    client.Timeout = TimeSpan.FromMinutes(5);
                    client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
                    var resp = await client.GetAsync(url, ct).ConfigureAwait(false);
                    resp.EnsureSuccessStatusCode();
                    var bytes = await resp.Content.ReadAsByteArrayAsync(ct).ConfigureAwait(false);
                    return Encoding.UTF8.GetString(bytes);
                }
                catch (Exception ex) when (attempt < 2)
                {
                    Log($"Download M3U falhou (tentativa {attempt + 1}/3): {ex.Message}. Retentando...");
                    await Task.Delay(2000 * (attempt + 1), ct).ConfigureAwait(false);
                }
            }

            throw new InvalidOperationException("Falha ao baixar M3U apos 3 tentativas.");
        }

        private void Log(string msg)
        {
            _logger.LogInformation("{Msg}", msg);
        }

        private static string GetDefaultStrmPath() =>
            Path.Combine(Plugin.AppPaths.ProgramDataPath, "midia-online", "strm");

        private static string GetStrmOutputPath(PluginConfiguration config)
        {
            if (!string.IsNullOrEmpty(config.StrmOutputPath))
                return config.StrmOutputPath;
            return GetDefaultStrmPath();
        }

        private static string GetGuideFilePath()
        {
            var dir = Path.Combine(Plugin.AppPaths.ProgramDataPath, "midia-online");
            return Path.Combine(dir, "guide.xml");
        }

        private async Task<string?> EnsureEpgGuideAsync(PluginConfiguration config, CancellationToken ct)
        {
            if (string.IsNullOrWhiteSpace(config.EpgUrl))
            {
                return null;
            }

            var guidePath = GetGuideFilePath();
            Directory.CreateDirectory(Path.GetDirectoryName(guidePath)!);

            if (File.Exists(guidePath))
            {
                try
                {
                    File.Delete(guidePath);
                }
                catch
                {
                    // Ignore and overwrite below.
                }
            }

            var sourcePath = config.EpgUrl;
            await using var target = new FileStream(
                guidePath,
                FileMode.Create,
                FileAccess.Write,
                FileShare.Read,
                81920,
                FileOptions.Asynchronous);

            if (Uri.TryCreate(config.EpgUrl, UriKind.Absolute, out var uri) && uri.Scheme.StartsWith("http", StringComparison.OrdinalIgnoreCase))
            {
                using var client = _httpClientFactory.CreateClient();
                client.Timeout = TimeSpan.FromSeconds(120);
                client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
                using var response = await client.GetAsync(config.EpgUrl, ct).ConfigureAwait(false);
                response.EnsureSuccessStatusCode();
                await using var source = await response.Content.ReadAsStreamAsync(ct).ConfigureAwait(false);
                sourcePath = response.RequestMessage?.RequestUri?.ToString() ?? config.EpgUrl;

                if (sourcePath.EndsWith(".gz", StringComparison.OrdinalIgnoreCase)
                    || sourcePath.EndsWith(".gzip", StringComparison.OrdinalIgnoreCase))
                {
                    await using var gzip = new GZipStream(source, CompressionMode.Decompress);
                    await gzip.CopyToAsync(target, ct).ConfigureAwait(false);
                }
                else
                {
                    await source.CopyToAsync(target, ct).ConfigureAwait(false);
                }
            }
            else
            {
                var localPath = Uri.TryCreate(config.EpgUrl, UriKind.Absolute, out var fileUri) && fileUri.Scheme.Equals(Uri.UriSchemeFile, StringComparison.OrdinalIgnoreCase)
                    ? fileUri.LocalPath
                    : config.EpgUrl;

                if (!File.Exists(localPath))
                {
                    throw new FileNotFoundException("XMLTV/EPG local file nao encontrado.", config.EpgUrl);
                }

                await using var source = new FileStream(localPath, FileMode.Open, FileAccess.Read, FileShare.Read, 81920, FileOptions.Asynchronous);
                if (localPath.EndsWith(".gz", StringComparison.OrdinalIgnoreCase)
                    || sourcePath.EndsWith(".gzip", StringComparison.OrdinalIgnoreCase))
                {
                    await using var gzip = new GZipStream(source, CompressionMode.Decompress);
                    await gzip.CopyToAsync(target, ct).ConfigureAwait(false);
                }
                else
                {
                    await source.CopyToAsync(target, ct).ConfigureAwait(false);
                }
            }

            var info = new FileInfo(guidePath);
            if (!info.Exists || info.Length == 0)
            {
                throw new InvalidOperationException("XMLTV/EPG sincronizado vazio.");
            }

            config.EpgLastSyncTime = DateTime.UtcNow;
            config.EpgLastError = null;
            return guidePath;
        }

        private async Task<string?> AutoFetchEpgAsync(PluginConfiguration config, List<M3uEntry> entries, CancellationToken ct)
        {
            var channelEntries = entries
                .Where(e => e.Type == "Canal")
                .ToList();

            if (channelEntries.Count == 0)
            {
                Log("Auto EPG: nenhum canal encontrado no M3U.");
                return null;
            }

            var dataDir = Path.Combine(Plugin.AppPaths.ProgramDataPath, "midia-online");
            var channelsXmlPath = Path.Combine(dataDir, "channels.xml");
            var guideXmlPath = Path.Combine(dataDir, "guide.xml");
            var guideXmlTempPath = Path.Combine(dataDir, "guide.xml.new");

            Directory.CreateDirectory(dataDir);

            try
            {
                var guidesJsonPath = Path.Combine(dataDir, "guides.json");
                var needDownloadGuides = true;
                if (File.Exists(guidesJsonPath))
                {
                    var fileInfo = new FileInfo(guidesJsonPath);
                    if (DateTime.UtcNow - fileInfo.LastWriteTimeUtc < TimeSpan.FromHours(24) && fileInfo.Length > 0)
                    {
                        needDownloadGuides = false;
                    }
                }

                if (needDownloadGuides)
                {
                    Log("Auto EPG: Baixando guides.json da iptv-org...");
                    var guidesJsonContent = await DownloadStringWithRetryAsync("https://iptv-org.github.io/api/guides.json", ct).ConfigureAwait(false);
                    if (string.IsNullOrEmpty(guidesJsonContent))
                    {
                        throw new InvalidOperationException("Falha ao baixar guides.json da iptv-org.");
                    }

                    await File.WriteAllTextAsync(guidesJsonPath, guidesJsonContent, ct).ConfigureAwait(false);
                }

                var guidesJson = await File.ReadAllTextAsync(guidesJsonPath, ct).ConfigureAwait(false);
                using var doc = JsonDocument.Parse(guidesJson);
                var catalog = MidiaStorageOnlineEpgMapper.BuildCatalog(channelEntries, doc);

                if (catalog.Channels.Count == 0)
                {
                    Log("Auto EPG: nenhum canal encontrado no guides.json da iptv-org.");
                    return null;
                }

                Log($"Auto EPG: {catalog.UniqueChannelCount} canais unicos resolvidos. Guia: {catalog.GuideMatchCount}, overrides: {catalog.OverrideCount}, sinteticos: {catalog.SyntheticCount}.");

                var xmlSettings = new XmlWriterSettings
                {
                    Indent = true,
                    Encoding = Encoding.UTF8
                };

                using (var writer = XmlWriter.Create(channelsXmlPath, xmlSettings))
                {
                    writer.WriteStartDocument();
                    writer.WriteStartElement("channels");

                    foreach (var ch in catalog.Channels)
                    {
                        writer.WriteStartElement("channel");
                        writer.WriteAttributeString("site", ch.Site);
                        writer.WriteAttributeString("site_id", ch.SiteId);
                        writer.WriteAttributeString("lang", ch.Lang);
                        writer.WriteAttributeString("xmltv_id", ch.XmltvId);
                        writer.WriteValue(ch.DisplayName);
                        writer.WriteEndElement();
                    }

                    writer.WriteEndElement();
                    writer.WriteEndDocument();
                }

                var guideUrls = catalog.Channels
                    .Select(ch => $"https://iptv-org.github.io/epg/{ch.Site}.xml")
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .ToList();

                if (guideUrls.Count == 0)
                {
                    Log("Auto EPG: nenhuma URL de guia encontrada para os canais resolvidos.");
                    return null;
                }

                Log($"Auto EPG: Baixando {guideUrls.Count} fontes de guia XMLTV...");
                var mergedXml = new StringBuilder();
                mergedXml.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
                mergedXml.AppendLine("<!DOCTYPE tv SYSTEM \"xmltv.dtd\">");
                mergedXml.AppendLine("<tv>");

                var sourcesLoaded = 0;
                foreach (var guideUrl in guideUrls)
                {
                    ct.ThrowIfCancellationRequested();
                    try
                    {
                        var xml = await DownloadStringWithRetryAsync(guideUrl, ct, maxRetries: 1).ConfigureAwait(false);
                        if (string.IsNullOrWhiteSpace(xml))
                        {
                            continue;
                        }

                        var xmlDoc = new XmlDocument();
                        xmlDoc.LoadXml(xml);
                        var programmes = xmlDoc.SelectNodes("//programme");
                        if (programmes is not null)
                        {
                            foreach (XmlNode prog in programmes)
                            {
                                mergedXml.AppendLine(prog.OuterXml);
                            }
                        }

                        sourcesLoaded++;
                    }
                    catch (Exception srcEx)
                    {
                        Log($"Auto EPG: Falha ao baixar guia {guideUrl}: {srcEx.Message}");
                    }
                }

                mergedXml.AppendLine("</tv>");

                var mergedContent = mergedXml.ToString();
                if (sourcesLoaded == 0 || mergedContent.Length < 500)
                {
                    throw new InvalidOperationException("Auto EPG: Nenhum dado de programa obtido das fontes.");
                }

                if (File.Exists(guideXmlTempPath))
                {
                    try { File.Delete(guideXmlTempPath); } catch { }
                }

                await File.WriteAllTextAsync(guideXmlTempPath, mergedContent, ct).ConfigureAwait(false);

                try
                {
                    if (System.IO.File.Exists(guideXmlPath))
                    {
                        System.IO.File.Replace(guideXmlTempPath, guideXmlPath, null, true);
                    }
                    else
                    {
                        System.IO.File.Move(guideXmlTempPath, guideXmlPath);
                    }
                }
                catch
                {
                    if (System.IO.File.Exists(guideXmlTempPath))
                    {
                        System.IO.File.Copy(guideXmlTempPath, guideXmlPath, true);
                        try { System.IO.File.Delete(guideXmlTempPath); } catch { }
                    }
                }

                var finalGuideInfo = new FileInfo(guideXmlPath);
                Log($"Auto EPG: Guia XMLTV gerado com sucesso: {finalGuideInfo.Length / 1024} KB de {sourcesLoaded} fontes.");
                config.EpgLastSyncTime = DateTime.UtcNow;
                config.EpgLastError = null;
                return guideXmlPath;
            }
            catch (Exception ex)
            {
                Log($"Auto EPG erro: {ex.Message}");
                config.EpgLastError = ex.Message;
                return null;
            }
        }

        private static int GetSitePriority(string? site)
        {
            if (string.IsNullOrEmpty(site)) return 0;
            site = site.ToLowerInvariant();
            if (site == "mi.tv") return 10;
            if (site == "claro.com.br") return 8;
            if (site == "sky.com.br") return 6;
            if (site == "meuguia.tv") return 4;
            return 1;
        }

        private static string BuildSyntheticXmlTvId(string site, string siteId, string? feed)
        {
            var parts = new[] { site, siteId, feed }
                .Where(p => !string.IsNullOrWhiteSpace(p))
                .Select(p => p!.Trim().ToLowerInvariant());

            var raw = string.Join("_", parts);
            var sb = new StringBuilder(raw.Length);
            foreach (var ch in raw)
            {
                sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
            }

            var normalized = Regex.Replace(sb.ToString(), "_+", "_").Trim('_');
            return string.IsNullOrWhiteSpace(normalized) ? Guid.NewGuid().ToString("N") : normalized;
        }

        private static string GetEffectiveTvgId(M3uEntry entry)
        {
            var approvedTvgId = MidiaStorageOnlineApprovedChannelMappings.TryGetEpgId(entry.TvgName, entry.Name, entry.TvgId);
            if (!string.IsNullOrWhiteSpace(approvedTvgId))
            {
                return approvedTvgId;
            }

            var mappedTvgId = MidiaStorageOnlineChannelMappings.ResolveTvgId(
                entry.TvgId,
                entry.TvgName,
                entry.GroupTitle,
                entry.Name);

            if (!string.IsNullOrWhiteSpace(mappedTvgId))
            {
                return mappedTvgId;
            }

            return BuildSyntheticXmlTvId(entry.TvgName ?? entry.GroupTitle ?? entry.Name, entry.GroupTitle ?? entry.Name, null);
        }

        private static void AppendEntryLinesWithInferredTvgId(StringBuilder builder, M3uEntry entry)
        {
            if (entry.RawLines.Count == 0)
            {
                return;
            }

            var effectiveTvgId = GetEffectiveTvgId(entry);
            var firstLine = entry.RawLines[0];
            if (firstLine.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase))
            {
                if (entry.Type == "Canal")
                {
                    firstLine = NormalizeChannelExtinfLine(firstLine, entry);
                }

                if (!string.IsNullOrWhiteSpace(effectiveTvgId)
                    && string.IsNullOrWhiteSpace(entry.TvgId))
                {
                    firstLine = EnsureTvgIdAttribute(firstLine, effectiveTvgId, entry.TvgName, entry.GroupTitle);
                }
            }

            builder.AppendLine(firstLine);
            for (var i = 1; i < entry.RawLines.Count; i++)
            {
                var line = entry.RawLines[i].TrimEnd('\r', '\n');
                if (i == entry.RawLines.Count - 1 && entry.Type == "Canal")
                {
                    line = MidiaStorageOnlineStreamProxy.BuildProxyUrl(line);
                }

                builder.AppendLine(line);
            }
        }

        private static string NormalizeChannelExtinfLine(string extinfLine, M3uEntry entry)
        {
            var line = extinfLine;
            line = ReplaceExtinfAttribute(line, "tvg-name", entry.TvgName ?? entry.Name);
            line = ReplaceExtinfAttribute(line, "group-title", entry.GroupTitle);
            if (string.IsNullOrWhiteSpace(entry.TvgLogo))
            {
                line = RemoveExtinfAttribute(line, "tvg-logo");
            }
            else
            {
                line = ReplaceExtinfAttribute(line, "tvg-logo", entry.TvgLogo);
            }

            line = ReplaceExtinfDisplayName(line, entry.Name);
            return line;
        }

        private static string NormalizeChannelDisplayName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return string.Empty;
            }

            var cleaned = Regex.Replace(name.Trim(), @"^\s*\d+\s*(?:[-:]\s*)?", string.Empty, RegexOptions.CultureInvariant);
            cleaned = Regex.Replace(cleaned, @"\s{2,}", " ");
            cleaned = cleaned.Trim();
            return string.IsNullOrWhiteSpace(cleaned) ? name.Trim() : cleaned;
        }

        private static string? NormalizeChannelLogo(string? logo)
        {
            if (string.IsNullOrWhiteSpace(logo))
            {
                return null;
            }

            if (!Uri.TryCreate(logo, UriKind.Absolute, out var uri))
            {
                return null;
            }

            if (!uri.Scheme.Equals(Uri.UriSchemeHttp, StringComparison.OrdinalIgnoreCase)
                && !uri.Scheme.Equals(Uri.UriSchemeHttps, StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            if (uri.Host.Equals("aaa55.top", StringComparison.OrdinalIgnoreCase))
            {
                return null;
            }

            return logo.Trim();
        }

        private static string? ResolveChannelLogo(string? tvgName, string? name, string? tvgId, string? tvgLogo)
        {
            var approvedLogo = MidiaStorageOnlineApprovedChannelMappings.TryGetLogoUrl(tvgName, name, tvgId);
            if (!string.IsNullOrWhiteSpace(approvedLogo))
            {
                return approvedLogo;
            }

            var workbookLogo = MidiaStorageOnlineWorkbookLogoMappings.TryGetLogoUrl(tvgName, name, tvgId);
            if (!string.IsNullOrWhiteSpace(workbookLogo))
            {
                return workbookLogo;
            }

            return NormalizeChannelLogo(tvgLogo);
        }

        private static string ReplaceExtinfDisplayName(string extinfLine, string displayName)
        {
            var commaIndex = GetExtinfDisplayNameSeparatorIndex(extinfLine);
            if (commaIndex < 0)
            {
                return $"{extinfLine},{displayName}";
            }

            return extinfLine.Substring(0, commaIndex + 1) + displayName;
        }

        private static string ReplaceExtinfAttribute(string extinfLine, string attribute, string? value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return extinfLine;
            }

            var sanitizedValue = value.Replace("\"", "'");
            var quotedPattern = $@"\b{Regex.Escape(attribute)}\s*=\s*""[^""]*""";
            var unquotedPattern = $@"\b{Regex.Escape(attribute)}\s*=\s*[^\s,]+";

            if (Regex.IsMatch(extinfLine, quotedPattern, RegexOptions.IgnoreCase))
            {
                return Regex.Replace(
                    extinfLine,
                    quotedPattern,
                    $"{attribute}=\"{sanitizedValue}\"",
                    RegexOptions.IgnoreCase);
            }

            if (Regex.IsMatch(extinfLine, unquotedPattern, RegexOptions.IgnoreCase))
            {
                return Regex.Replace(
                    extinfLine,
                    unquotedPattern,
                    $"{attribute}=\"{sanitizedValue}\"",
                    RegexOptions.IgnoreCase);
            }

            var insertAt = extinfLine.IndexOf(',');
            if (insertAt < 0)
            {
                insertAt = extinfLine.Length;
            }

            return extinfLine.Insert(insertAt, $" {attribute}=\"{sanitizedValue}\"");
        }

        private static string RemoveExtinfAttribute(string extinfLine, string attribute)
        {
            var quotedPattern = $@"\s+\b{Regex.Escape(attribute)}\s*=\s*""[^""]*""";
            var unquotedPattern = $@"\s+\b{Regex.Escape(attribute)}\s*=\s*[^\s,]+";

            var cleaned = Regex.Replace(extinfLine, quotedPattern, string.Empty, RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, unquotedPattern, string.Empty, RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, @"\s{2,}", " ");
            return cleaned;
        }

        private static int GetExtinfDisplayNameSeparatorIndex(string extinfLine)
        {
            if (string.IsNullOrEmpty(extinfLine))
            {
                return -1;
            }

            var inQuotes = false;
            var startIdx = extinfLine.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase)
                ? "#EXTINF:".Length
                : 0;

            for (var i = startIdx; i < extinfLine.Length; i++)
            {
                var c = extinfLine[i];
                if (c == '"')
                {
                    inQuotes = !inQuotes;
                }
                else if (c == ',' && !inQuotes)
                {
                    return i;
                }
            }

            return -1;
        }

        private static string EnsureTvgIdAttribute(string extinfLine, string tvgId, string? tvgName, string? groupTitle)
        {
            var quotedPattern = @"\btvg-id\s*=\s*""[^""]*""";
            var unquotedPattern = @"\btvg-id\s*=\s*[^\s,]+";

            if (Regex.IsMatch(extinfLine, quotedPattern, RegexOptions.IgnoreCase))
            {
                extinfLine = Regex.Replace(
                    extinfLine,
                    quotedPattern,
                    $"tvg-id=\"{tvgId}\"",
                    RegexOptions.IgnoreCase);
            }
            else if (Regex.IsMatch(extinfLine, unquotedPattern, RegexOptions.IgnoreCase))
            {
                extinfLine = Regex.Replace(
                    extinfLine,
                    unquotedPattern,
                    $"tvg-id=\"{tvgId}\"",
                    RegexOptions.IgnoreCase);
            }
            else
            {
                var insertAt = extinfLine.IndexOf(',');
                if (insertAt < 0)
                {
                    insertAt = extinfLine.Length;
                }

                var attrs = new StringBuilder();
                attrs.Append($" tvg-id=\"{tvgId}\"");
                if (!string.IsNullOrWhiteSpace(tvgName) && !Regex.IsMatch(extinfLine, @"\btvg-name\s*=", RegexOptions.IgnoreCase))
                {
                    attrs.Append($" tvg-name=\"{tvgName}\"");
                }
                if (!string.IsNullOrWhiteSpace(groupTitle) && !Regex.IsMatch(extinfLine, @"\bgroup-title\s*=", RegexOptions.IgnoreCase))
                {
                    attrs.Append($" group-title=\"{groupTitle}\"");
                }

                return extinfLine.Insert(insertAt, attrs.ToString());
            }

            return extinfLine;
        }

        private async Task<string?> DownloadStringWithRetryAsync(string url, CancellationToken ct, int maxRetries = 2)
        {
            for (int i = 0; i <= maxRetries; i++)
            {
                try
                {
                    using var client = _httpClientFactory.CreateClient();
                    client.Timeout = TimeSpan.FromSeconds(60);
                    client.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36");
                    return await client.GetStringAsync(url, ct).ConfigureAwait(false);
                }
                catch (Exception ex) when (i < maxRetries)
                {
                    Log($"Download falhou (tentativa {i + 1}/{maxRetries + 1}): {ex.Message}. Retentando...");
                    await Task.Delay(1000 * (i + 1), ct).ConfigureAwait(false);
                }
            }
            return null;
        }

        private class MappedChannel
        {
            public string Site { get; set; } = "";
            public string SiteId { get; set; } = "";
            public string Lang { get; set; } = "pt";
            public string XmltvId { get; set; } = "";
            public string Name { get; set; } = "";
        }

        private void RegisterXmlTvListingProvider(string guidePath, PluginConfiguration config)
        {
            var liveTvConfig = _configurationManager.GetConfiguration<LiveTvOptions>("livetv");
            var providers = liveTvConfig.ListingProviders.ToList();
            var provider = providers.FirstOrDefault(p =>
                string.Equals(p.Id, config.EpgListingProviderId, StringComparison.OrdinalIgnoreCase)
                || string.Equals(p.ListingsId, "Midia Storage Online EPG", StringComparison.OrdinalIgnoreCase));

            if (provider is null)
            {
                provider = new ListingsProviderInfo
                {
                    Id = Guid.NewGuid().ToString("N"),
                    Type = "xmltv"
                };
                providers.Add(provider);
            }

            provider.Type = "xmltv";
            provider.ListingsId = "Midia Storage Online EPG";
            provider.Path = guidePath;
            provider.EnableAllTuners = true;
            provider.EnabledTuners = Array.Empty<string>();
            provider.PreferredLanguage = "pt-BR";
            config.EpgListingProviderId = provider.Id;

            liveTvConfig.ListingProviders = providers.ToArray();
            _configurationManager.SaveConfiguration("livetv", liveTvConfig);
        }

        private async Task UpdateLiveTvChannelItemsAsync(IEnumerable<M3uEntry> entries, CancellationToken ct)
        {
            var logoByName = entries
                .Where(e => e.Type == "Canal")
                .Where(e => !string.IsNullOrWhiteSpace(e.TvgLogo))
                .GroupBy(e => NormalizeChannelDisplayName(e.Name), StringComparer.OrdinalIgnoreCase)
                .ToDictionary(g => g.Key, g => g.First().TvgLogo!, StringComparer.OrdinalIgnoreCase);

            var channelItems = _libraryManager.GetItemList(new InternalItemsQuery
            {
                IncludeItemTypes = new[] { BaseItemKind.LiveTvChannel }
            });

            foreach (var baseItem in channelItems)
            {
                ct.ThrowIfCancellationRequested();

                if (baseItem is not LiveTvChannel channelItem)
                {
                    continue;
                }

                var normalizedName = NormalizeChannelDisplayName(channelItem.Name);
                var changed = false;

                if (!string.Equals(channelItem.Name, normalizedName, StringComparison.Ordinal))
                {
                    channelItem.Name = normalizedName;
                    changed = true;
                }

                if (!string.Equals(channelItem.ForcedSortName, normalizedName, StringComparison.Ordinal))
                {
                    channelItem.ForcedSortName = normalizedName;
                    changed = true;
                }

                if (logoByName.TryGetValue(normalizedName, out var localLogoUrl)
                    && !string.IsNullOrWhiteSpace(localLogoUrl))
                {
                    var currentImagePath = channelItem.GetImages(ImageType.Primary).FirstOrDefault()?.Path;
                    if (!string.Equals(currentImagePath, localLogoUrl, StringComparison.OrdinalIgnoreCase))
                    {
                        channelItem.SetImagePath(ImageType.Primary, localLogoUrl);
                        changed = true;
                    }
                }

                if (changed)
                {
                    await _libraryManager.UpdateItemAsync(channelItem, channelItem.GetParent(), ItemUpdateType.MetadataImport, ct).ConfigureAwait(false);
                }
            }
        }

        private List<M3uEntry> ParseM3u(string raw, out string headerLine)
        {
            var entries = new List<M3uEntry>();
            headerLine = "#EXTM3U\n";
            var lines = raw.Split('\n');

            if (lines.Length > 0 && lines[0].StartsWith("#EXTM3U", StringComparison.Ordinal))
                headerLine = lines[0].TrimEnd('\r') + "\n";

            string? currentExtinf = null;
            var currentLines = new List<string>();

            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed.Length == 0) continue;

                if (trimmed.StartsWith("#EXTINF:", StringComparison.Ordinal))
                {
                    currentExtinf = line;
                    currentLines = new List<string> { line.TrimEnd('\r') + "\n" };
                }
                else if (trimmed.StartsWith('#'))
                {
                    if (currentExtinf != null)
                        currentLines.Add(line.TrimEnd('\r') + "\n");
                }
                else
                {
                    if (currentExtinf != null)
                    {
                        var cleanUrl = trimmed;
                        currentLines.Add(cleanUrl + "\n");
                        var entry = ParseEntry(currentExtinf, cleanUrl, currentLines);
                        entries.Add(entry);
                        currentExtinf = null;
                    }
                }
            }

            return entries;
        }

        private M3uEntry ParseEntry(string extinfLine, string url, List<string> rawLines)
        {
            string name = ExtractDisplayName(extinfLine);
            var tvgId = ExtractAttribute(extinfLine, "tvg-id");
            var tvgName = ExtractAttribute(extinfLine, "tvg-name");
            var groupTitle = ExtractAttribute(extinfLine, "group-title");
            var tvgLogo = ExtractAttribute(extinfLine, "tvg-logo");

            string type;
            if (IsMovieEntry(url))
                type = "Filme";
            else if (IsSeriesEntry(url))
                type = "Serie";
            else
                type = "Canal";

            if (type == "Canal")
            {
                tvgLogo = ResolveChannelLogo(tvgName, name, tvgId, tvgLogo);
            }

            string showName = name;
            string season = "Season 1";

            if (type == "Serie")
            {
                var epMatch = _epRegex.Match(name);
                if (epMatch.Success)
                {
                    showName = epMatch.Groups[1].Value.Trim();
                    season = "Season " + epMatch.Groups[2].Value;
                    var episodeTitle = epMatch.Groups[4].Value.Trim();
                    if (!string.IsNullOrEmpty(episodeTitle))
                        name = episodeTitle;
                }
            }

            return new M3uEntry
            {
                Name = name,
                Url = url,
                Type = type,
                RawLines = rawLines,
                ShowName = showName,
                Season = season,
                TvgId = tvgId,
                TvgName = tvgName,
                GroupTitle = groupTitle,
                TvgLogo = tvgLogo
            };
        }

        private static string SanitizeName(string name)
        {
            name = name.Replace(":", " - ", StringComparison.Ordinal);
            name = name.Replace("_", " - ", StringComparison.Ordinal);
            name = name.Replace("&", "e", StringComparison.Ordinal);

            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                if (c == '\uFFFD' || char.IsControl(c) || _invalidFileNameChars.Contains(c))
                {
                    sb.Append('_');
                }
                else
                {
                    sb.Append(c);
                }
            }
            return Regex.Replace(sb.ToString().TrimEnd('.', ' '), @"\s+", " ").Trim();
        }

        private static async Task<bool> HasSameContentAsync(string filePath, string expectedContent, CancellationToken ct)
        {
            if (!System.IO.File.Exists(filePath))
            {
                return false;
            }

            var currentContent = await System.IO.File.ReadAllTextAsync(filePath, ct).ConfigureAwait(false);
            return string.Equals(currentContent.Trim(), expectedContent.Trim(), StringComparison.Ordinal);
        }

        private static string BuildEntryDedupKey(M3uEntry entry)
        {
            if (string.Equals(entry.Type, "Filme", StringComparison.OrdinalIgnoreCase))
            {
                return $"Filme|{SanitizeName(entry.Name)}";
            }

            if (string.Equals(entry.Type, "Serie", StringComparison.OrdinalIgnoreCase))
            {
                return $"Serie|{SanitizeName(entry.ShowName)}|{SanitizeName(entry.Season)}|{SanitizeName(entry.Name)}";
            }

            var stableChannelKey = !string.IsNullOrWhiteSpace(entry.TvgId)
                ? entry.TvgId!.Trim()
                : NormalizeChannelDisplayName(entry.TvgName ?? entry.Name);

            return $"Canal|{stableChannelKey}|{entry.Url.Trim()}";
        }

        private static string ExtractDisplayName(string extinfLine)
        {
            if (string.IsNullOrEmpty(extinfLine))
                return "Unknown";

            bool inQuotes = false;
            int commaIdx = -1;
            int startIdx = 0;
            if (extinfLine.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase))
            {
                startIdx = "#EXTINF:".Length;
            }

            for (int i = startIdx; i < extinfLine.Length; i++)
            {
                char c = extinfLine[i];
                if (c == '"')
                {
                    inQuotes = !inQuotes;
                }
                else if (c == ',' && !inQuotes)
                {
                    commaIdx = i;
                    break;
                }
            }

            string name;
            if (commaIdx >= 0)
            {
                name = extinfLine.Substring(commaIdx + 1).Trim();
            }
            else
            {
                var lastQuote = extinfLine.LastIndexOf('"');
                if (lastQuote >= 0 && lastQuote < extinfLine.Length - 1)
                {
                    name = extinfLine.Substring(lastQuote + 1).Trim();
                }
                else
                {
                    name = extinfLine;
                    if (name.StartsWith("#EXTINF:", StringComparison.OrdinalIgnoreCase))
                    {
                        var match = Regex.Match(name, @"^#EXTINF:\s*[-+]?\d+\s*");
                        if (match.Success)
                        {
                            name = name.Substring(match.Length);
                        }
                    }
                    name = name.Trim();
                }
            }

            name = CleanLeftoverAttributes(name);
            return string.IsNullOrEmpty(name) ? "Unknown" : name;
        }

        private static string? ExtractAttribute(string extinfLine, string attribute)
        {
            if (string.IsNullOrEmpty(extinfLine))
            {
                return null;
            }

            var match = Regex.Match(extinfLine, $@"\b{Regex.Escape(attribute)}\s*=\s*""([^""]*)""", RegexOptions.IgnoreCase);
            if (match.Success)
            {
                return match.Groups[1].Value;
            }

            match = Regex.Match(extinfLine, $@"\b{Regex.Escape(attribute)}\s*=\s*([^\s,]+)", RegexOptions.IgnoreCase);
            return match.Success ? match.Groups[1].Value : null;
        }

        private static string CleanLeftoverAttributes(string name)
        {
            if (string.IsNullOrEmpty(name))
                return name;

            var cleaned = name;
            cleaned = Regex.Replace(cleaned, @"\b(tvg-logo|tvg-name|tvg-id|group-title|tvg-country|tvg-language|tvg-chno|logo|channel-id)\s*=\s*""[^""]*""", "", RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, @"\b(tvg-logo|tvg-name|tvg-id|group-title|tvg-country|tvg-language|tvg-chno|logo|channel-id)\s*=\s*[^\s]*", "", RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, @"\s+", " ");
            cleaned = cleaned.Trim(' ', ',', '-', '_');
            return cleaned;
        }

        private static bool IsMovieEntry(string url)
        {
            return url.Contains("/movie/", StringComparison.OrdinalIgnoreCase);
        }

        private static bool IsSeriesEntry(string url)
        {
            return url.Contains("/series/", StringComparison.OrdinalIgnoreCase);
        }

        private static string GetCanaisFilePath()
        {
            var dir = Path.Combine(Plugin.AppPaths.ProgramDataPath, "midia-online");
            return Path.Combine(dir, "canais.m3u8");
        }

        public IEnumerable<TaskTriggerInfo> GetDefaultTriggers()
        {
            return new[]
            {
                new TaskTriggerInfo
                {
                    Type = TaskTriggerInfoType.DailyTrigger,
                    TimeOfDayTicks = TimeSpan.FromHours(5.5).Ticks
                }
            };
        }

        private class M3uEntry : IMidiaStorageOnlineM3uEntry
        {
            public string Name { get; set; } = "";
            public string Url { get; set; } = "";
            public string Type { get; set; } = "Canal";
            public string ShowName { get; set; } = "";
            public string Season { get; set; } = "Season 1";
            public List<string> RawLines { get; set; } = new();
            public string? TvgId { get; set; }
            public string? TvgName { get; set; }
            public string? GroupTitle { get; set; }
            public string? TvgLogo { get; set; }
        }
    }
}

