// <auto-generated />
#nullable disable

using System;
using System.Collections.Generic;
using MediaBrowser.Common.Configuration;
using MediaBrowser.Common.Plugins;
using MediaBrowser.Model.Plugins;
using MediaBrowser.Model.Serialization;
using MediaBrowser.Providers.Plugins.MidiaStorageOnline.Configuration;

namespace MediaBrowser.Providers.Plugins.MidiaStorageOnline
{
    public class Plugin : BasePlugin<PluginConfiguration>, IHasWebPages
    {
        public Plugin(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer)
            : base(applicationPaths, xmlSerializer)
        {
            Instance = this;
        }

        public static Plugin Instance { get; private set; }
        public static IApplicationPaths AppPaths => Instance!.ApplicationPaths;

        public override Guid Id => new Guid("f956680c-9a06-4cac-93d2-b57cd6061756");

        public override string Name => "Midia Storage Online";

        public override string Description => "Baixa lista M3U, gera arquivos .strm e pode cachear XMLTV/EPG para o MulletaFlix.";

        public override string ConfigurationFileName => "MulletaFlix.Plugin.MidiaStorageOnline.xml";

        public override PluginInfo GetPluginInfo()
        {
            var info = base.GetPluginInfo();
            info.Version = new Version(1, 0, 0, 0);
            return info;
        }

        public IEnumerable<PluginPageInfo> GetPages()
        {
            yield return new PluginPageInfo
            {
                Name = Name,
                EmbeddedResourcePath = GetType().Namespace + ".Configuration.config.html"
            };
        }
    }
}

